export const PERMISSIONS = {
  WORKSPACE_UPDATE: "WORKSPACE_UPDATE",
  MEMBER_INVITE: "MEMBER_INVITE",
  MEMBER_REMOVE: "MEMBER_REMOVE",
  MEMBER_ROLE_CHANGE: "MEMBER_ROLE_CHANGE",

  GOAL_CREATE: "GOAL_CREATE",
  GOAL_UPDATE: "GOAL_UPDATE",
  GOAL_DELETE: "GOAL_DELETE",

  ANNOUNCEMENT_CREATE: "ANNOUNCEMENT_CREATE",
  ANNOUNCEMENT_UPDATE: "ANNOUNCEMENT_UPDATE",
  ANNOUNCEMENT_DELETE: "ANNOUNCEMENT_DELETE",

  ACTION_ITEM_CREATE: "ACTION_ITEM_CREATE",
  ACTION_ITEM_UPDATE: "ACTION_ITEM_UPDATE",
  ACTION_ITEM_DELETE: "ACTION_ITEM_DELETE",

  AUDIT_VIEW: "AUDIT_VIEW",
  ANALYTICS_EXPORT: "ANALYTICS_EXPORT"
};

const ROLE_PERMISSIONS = {
  OWNER: Object.values(PERMISSIONS),

  ADMIN: [
    PERMISSIONS.WORKSPACE_UPDATE,
    PERMISSIONS.MEMBER_INVITE,
    PERMISSIONS.MEMBER_REMOVE,

    PERMISSIONS.GOAL_CREATE,
    PERMISSIONS.GOAL_UPDATE,
    PERMISSIONS.GOAL_DELETE,

    PERMISSIONS.ANNOUNCEMENT_CREATE,
    PERMISSIONS.ANNOUNCEMENT_UPDATE,
    PERMISSIONS.ANNOUNCEMENT_DELETE,

    PERMISSIONS.ACTION_ITEM_CREATE,
    PERMISSIONS.ACTION_ITEM_UPDATE,
    PERMISSIONS.ACTION_ITEM_DELETE,

    PERMISSIONS.AUDIT_VIEW,
    PERMISSIONS.ANALYTICS_EXPORT
  ],

  MEMBER: [
    PERMISSIONS.GOAL_CREATE,
    PERMISSIONS.GOAL_UPDATE,

    PERMISSIONS.ACTION_ITEM_CREATE,
    PERMISSIONS.ACTION_ITEM_UPDATE,

    PERMISSIONS.ANALYTICS_EXPORT
  ]
};

export function hasPermission(role, permission) {
  return ROLE_PERMISSIONS[role]?.includes(permission) || false;
}

export function requirePermission(membership, permission) {
  if (!membership || !hasPermission(membership.role, permission)) {
    const error = new Error("You do not have permission to perform this action");
    error.statusCode = 403;
    throw error;
  }
}